include:
  - project: 'vivarium/th2/pipelines'
    ref: test
    file: '/.gitlab-ci-common.yml'

stages:
  - meta
  - build
  - build-docker
  - test
  - publish
  - notify

variables:
  APP_NAME: "th2-codec-generic"
  MAJOR_VERSION: "1"
  MINOR_VERSION: "2"
  MAINTENANCE_VERSION: '0'

build:
  extends: .build-template
  variables:
    DOCKER_INTERMEDIATE_TAG: "${CI_COMMIT_SHA}"
    DOCKER_BUILD_TARGET: "--target build"
  dependencies:
    - makeMetaEnv

build-dockers:
  extends: .build-template
  stage: build-docker
  variables:
    DOCKER_INTERMEDIATE_TAG: "${CI_COMMIT_SHA}-${PROJECT_NAME}"
    DOCKER_BUILD_ARGS: >-
      --build-arg project_name=${PROJECT_NAME}
      --build-arg source_docker_repository=${REGISTRY}
  dependencies:
    - build
    - makeMetaEnv
  parallel:
    matrix:
      - PROVIDER: codecs
        PROJECT_NAME:
          - codec-fast
          - codec-fix
          - codec-itch
          - codec-ntg
          - codec-tcpip

docker_publish:
  extends: .docker-publish-template
  variables:
    IMAGE_NAME: "th2-${PROJECT_NAME}"
    DOCKER_SOURCE_TAG: "${CI_COMMIT_SHA}-${PROJECT_NAME}"
  dependencies:
    - makeMetaEnv
  parallel:
    matrix:
      - PROVIDER: codecs
        PROJECT_NAME:
          - codec-fast
          - codec-fix
          - codec-itch
          - codec-ntg
          - codec-tcpip