{
  "verifyMessageStructure": "true",
  "decodeByDictionary": "true",
  "depersonalizationIncomingMessages": "false",
  "includeMicroseconds": "true",
  "fieldConverterClassName": "com.exactpro.sf.services.fix.FixFieldConverter"
}