name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  workflow_dispatch:
  push:
    branches:
      - dev-version-*
    paths:
      - gradle.properties

jobs:
  build:
    strategy:
      matrix:
        proto:
          - codec-fast
          - codec-fix
          - codec-itch
          - codec-ntg
          - codec-soup
    uses: th2-net/.github/.github/workflows/matrix-java-docker.yml@main
    with:
      runsOn: ubuntu-20.04
      projectName: ${{ matrix.proto }}
      build-target: 'Docker'
      docker-username: ${{ github.actor }}
      devRelease: true
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
