name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches:
      - master
      - version-*
    paths:
      - gradle.properties

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        proto:
          - codec-fast
          - codec-fix
          - codec-itch
          - codec-ntg
          - codec-soup
    uses: th2-net/.github/.github/workflows/matrix-java-docker.yml@th2-4135-matrix-workflow
    with:
      runsOn: ubuntu-20.04
      projectName: ${{ matrix.proto }}
      build-target: 'Docker'
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}

